### ISSUE TITLE
Some `clickDispatchAction` not working

### ISSUE THREAD

**Issue by ProLoser** [inakineitor/touch-bar-utility#18]
This is my config:
```js
exports.configuration = [{
  type: 'button',
  label: 'Project',
  clickDispatchAction: 'tree-view:toggle'
}, {
  type: 'button',
  label: 'Diagnostics',
  clickDispatchAction: 'diagnostics:toggle-table',
}, {
  type: 'button',
  label: 'Outline',
  clickDispatchAction: 'outline-view:toggle',
}, {
  type: 'button',
  label: 'Git',
  clickDispatchAction: 'github:toggle-git-tab',
}];
```

The `diagnostics:toggle-table` and `outline-view:toggle` commands are throwing errors. I have Atom-IDE installed and enabled and calling those commands directly or through the palette works fine.

**Comment by inakineitor** [comment]
While testing I have tried overriding the checks for `diagnostics` and for `outline-view`, but nothing happens when I click the buttons. Could you please post an image of the error and an image of the proper functioning of the two commands. Are these packages part of Atom, or have you installed them?

**Comment by ProLoser** [comment]
They are part of atom ide https://atom.io/packages/atom-ide-ui https://ide.atom.io/

**Comment by inakineitor** [comment]
I found the problem. It the cause was that the package `atom-ide-ui` has many sub-packages. I have fixed it and added a way to use these kinds of packages.
You have to use the click function like so:
```
{
  type: 'button',
  label: 'Diagnostics',
  click: () => {
    dispatchAction('diagnostics:toggle-table', 'workspace', true);
  },
  backgroundColor: '#4899a8'
}
```
**For it to work, there must be a third argument in dispatchAction with the value** `true`

I will publish the new update shortly.
