### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by david-pivonka** [inakineitor/touch-bar-utility#4]
Hi, I'm here again. 
I'm using this json
`[
  {
    "type": "button",
    "label": "Exposé",
    "clickDispatchAction": "expose:toggle"
  }
]`
and it always shows this popup:
<img width="1175" alt="obrazek aplikace zpravy 2373697570" src="https://user-images.githubusercontent.com/4690621/28768975-0079a958-75da-11e7-815e-b0cd65f03214.png">
but as you can see, expose package is loaded and activated.

**Comment by inakineitor** [comment]
There are four possible states for a package.
*    The first state indicates that the package is installed.
*    The second state indicates that the package is enabled.
*    The third state indicates that the package is loaded into the enviroment.
*    The forth state indicates that the package is activated.

touch-bar-utility first checks if the package is installed and then checks if the package is enabled. No popup has appeard, so Exposé has been detected.

The error you see ocurs if the package is not loaded <strong>OR</strong> not activated.

I checked the Exposé github repository and it turns out, that you have to manually activate the package by issuing the expose:toggle command.

So every time you open Atom, you have up to go to the Packages tab and manually toggle Exposé. After you have done that, the command should be able to be issued by the touch bar.

**Comment by apemsel** [comment]
I have a similar problem with built-in commands like command-palette:toggle. They work after restarting touch-bar, but not after restarting Atom.

**Comment by inakineitor** [comment]
The packages' states are reset when Atom relaunches. The installed and enabled states remain active, but the activated state doesn't. You have to manually toggle one time command-palette through the Packages - command-palette - toggle to activate it every time you start Atom before you can use it with the TouchBar. Some packages activated automatically, but others must be toggle one before getting activated. Sadly that is nothing I can do as I cannot remotely activate other packages from mine.

**Comment by inakineitor** [comment]
I have coded the undefined checking and it now works fine. When I can I will update the package. I am. Ot currently with a co.puter that has git installed.
